name: dpug

environment:
  sdk: ^3.5.3

dev_dependencies:
  analyzer: ^6.8.0
  analyzer_plugin: ^0.11.3
  build: ^2.4.1
  build_runner: ^2.4.8
  build_test: ^2.2.0
  source_gen: ^1.5.0
  test: ^1.24.0
  code_builder: ^4.10.0
  dart_style: ^2.3.7
