name: xsoulspace_foundation
description: Shared utils, extensions, and helpers.
version: 0.0.9
homepage: https://github.com/xsoulspace/life_hooks/packages/xsoulspace_foundation
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  infinite_scroll_pagination: ^4.1.0
  shared_preferences: ^2.4.0
  store_checker: ^1.6.0
  uuid: ^4.5.1
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  xsoulspace_lints: ^0.0.13
